# Generated by Django 5.0.1 on 2024-01-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('employee_id', models.CharField(max_length=256, unique=True)),
                ('designation', models.CharField(max_length=256)),
                ('joining_date', models.DateField()),
                ('account_number', models.CharField(max_length=256)),
                ('ifsc', models.CharField(max_length=256)),
                ('pf_number', models.CharField(max_length=256)),
                ('uan_no', models.CharField(max_length=256)),
                ('pan_no', models.CharField(max_length=256)),
                ('baisc_salary', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('conv', models.IntegerField()),
                ('special_allowance', models.IntegerField(default=0)),
                ('pf', models.IntegerField()),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.bank')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baisc_salary', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('conv', models.IntegerField()),
                ('special_allowance', models.IntegerField(default=0)),
                ('pf', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
