# Generated by Django 5.0.1 on 2024-01-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_code',
            field=models.CharField(default='SPCPE', max_length=256),
        ),
        migrations.AddField(
            model_name='employee',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
