# Generated by Django 5.0.1 on 2024-01-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_company_code_employee_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='conv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
