# Generated by Django 5.0.1 on 2024-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_conv_alter_employee_pf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_code',
            field=models.CharField(blank=True, default='SPCPE', max_length=256, null=True),
        ),
    ]
