# Generated by Django 5.0.1 on 2024-01-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_payslip_month_payslip_year_alter_payslip_conv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='month',
        ),
    ]
