# Generated by Django 5.0.1 on 2024-01-30 06:14

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_payslip_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUG', 'AUGUST'), ('SEPT', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default=employee.models.Months['January'], max_length=256),
        ),
    ]
