# Generated by Django 5.0.1 on 2024-01-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_payslip_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='baisc_salary',
            new_name='basic_salary',
        ),
        migrations.AlterField(
            model_name='payslip',
            name='baisc_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='conv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='hra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='special_allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
