# Generated by Django 5.0.1 on 2024-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_baisc_salary_employee_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_no',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
